added thumbnail for Samsung
andOTP/andOTP pull request #623
Opened 2020-08-11 23:43 UTC by ivanlewin

2020-08-12 07:38 UTC, ziegenberg commented
There is already a PR for a Samsung thumbnail. I'll have a look at it and compare them.

2020-08-12 14:06 UTC, ivanlewin commented
Thanks, I missed it. I added a black wordmark, which seems to be the current logo, taken from samsung.com

2020-08-26 21:00 UTC, ziegenberg commented
This are two Screenshots from this Samsung-thumbnail and the one I would have used (see commit b788ae5fc7632402ae2d4527f7ce6a2bbe06114d in #573). I prefer the black wordmark from this PR, although it appears rather small, therefore might be hard to read on small screens or low resolutions and it's not very square.

![Screenshot_1597345652](https://user-images.githubusercontent.com/856916/91355976-3a53ec80-e7ef-11ea-82be-1ba65a24fc29.png)

![Screenshot_1597345776](https://user-images.githubusercontent.com/856916/91355983-3d4edd00-e7ef-11ea-8df6-843a40d342a1.png)

2020-08-26 21:03 UTC, ziegenberg requested changes
There's only one small thing and then it's good to go.

2020-08-26 21:03 UTC, ziegenberg commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:4.0.1'
Please do not update build tools when committing a thumbnail. This should go into a separate PR.

2020-08-26 23:16 UTC, ivanlewin commented
Yes, I know it's not perfectly square, it bothers me too. I took the vector from Samsung's website so I think we have to deal with it sadly

2020-08-27 05:44 UTC, ziegenberg approved these changes

2020-08-28 03:43 UTC, merged

2020-09-27 20:53 UTC, ziegenberg commented
Fixed #562.