closes #662
andOTP/andOTP pull request #663
Opened 2020-10-05 22:30 UTC by philipreimer

add Mattermost thumbnail

2020-10-06 19:00 UTC, ziegenberg requested changes
A few minor adjustments but looks good overall!

2020-10-06 22:05 UTC, philipreimer commented on app/src/main/res/drawable/thumb_mattermost.xml
> +      android:pathData="m665.539,666.653l-4.84,-0c-0.579,-0 -1.085,-0.469 -1.121,-1.048L657.919,644.368 651.089,659.718c-0.18,0.433 -0.575,0.687 -1.049,0.687l-4.332,-0c-0.433,-0 -0.832,-0.254 -1.049,
Done

2020-10-06 22:06 UTC, philipreimer commented on app/src/main/res/drawable/thumb_mattermost.xml
> +    android:width="666.6667dp"
Resized. Hope this is ok now.

2020-10-18 17:55 UTC, ziegenberg approved these changes

2020-10-18 18:03 UTC, merged